# config.ini
# Configuración para leer el Circutor Computer SMART III / Smart Computer III
# por Modbus RTU usando un convertidor RS485-USB.
#
# Estructura esperada:
#
# MODBUS_PROJECT/
# ├── .venv/
# ├── config.ini
# ├── read.py
# ├── requirements.txt
# └── data/
#     └── raw/
#
# Para ejecutar:
#
#   python read.py
#
# Para detener la lectura continua:
#
#   Ctrl + C


[serial]
# Puerto serial donde está conectado el convertidor RS485-USB.
#
# En Windows normalmente será:
# port = COM3
# port = COM4
# port = COM5
# port = COM8
#
# En Raspberry Pi / Linux normalmente será:
# port = /dev/ttyUSB0
# port = /dev/ttyACM0
#
# En Raspberry Pi es mejor usar /dev/serial/by-id/... cuando ya identifiques el adaptador.
port = COM8

# Parámetros Modbus RTU.
# El equipo suele venir por defecto en 19200, none, 8 bits, 1 stop bit.
baudrate = 19200
parity = none
bytesize = 8
stopbits = 1
timeout = 1.0


[device]
# Num. periférico / Slave ID Modbus del controlador.
# Debe estar entre 1 y 254.
slave_id = 1

# Modelo del equipo según número de relés:
# 6, 12 o 14
max_relays = 14


[read]
# 1 = una sola lectura y termina.
# 0 = lectura continua cada interval_seconds.
once = 0

# Intervalo de lectura en segundos.
# 10 = tomar una lectura cada 10 segundos.
interval_seconds = 10

# Reintentos por cada registro leído.
retries = 1

# 1 = leer relés, alarmas, entradas y salidas digitales.
# 0 = leer solo variables eléctricas principales.
status = 1

# 1 = leer también configuración básica del equipo:
# slave, velocidad, paridad, bits, stopbits.
# Para operación normal puede quedarse en 0.
config_read = 0


[logging]
# Ruta del CSV de salida.
# Si la ruta es relativa, se interpreta desde la carpeta MODBUS_PROJECT.
csv_path = data/raw/smart_computer_iii_data.csv

# 1 = imprime JSON completo.
# 0 = imprime resumen legible en terminal.
print_json = 0

# 1 = activa debug detallado de minimalmodbus.
# Útil solo para diagnóstico.
debug = 0


[scaling]
# Factor de escala para tensión.
#
# En la tabla del manual aparece V/100, pero el ejemplo Modbus del manual indica:
# 0x0000084D = 2125 => 212.5 V
#
# Por eso el valor recomendado inicial es 0.1.
# Si en campo ves una tensión 10 veces mayor o menor, probar:
# voltage_scale = 0.01
# o
# voltage_scale = 1
voltage_scale = 0.1
